### PR TITLE
[JENKINS-66455] Support Eclipse Temurin

### PR DESCRIPTION
**Pull request by basil**
This PR does a few things:

- Updates the plugin to the latest build infrastructure
- Renames any user-visible strings from AdoptOpenJDK to Adoptium or Eclipse Temurin, while preserving any Java class names and programmatic strings as-is for backward compatibility
- Updates the tests to use the latest output from the crawler

To test this change I successfully installed Eclipse Temurin 11.0.16.1 with these changes.

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]
Change looks good to me.

**Comment by bguerin** [comment]
supersedes https://github.com/jenkinsci/adoptopenjdk-plugin/pull/21

**Comment by halkeye** [comment]
cc @hrmohr

**Comment by MarkEWaite** [comment]
I'm running with the build from this pull request in [my plugins.txt](https://github.com/MarkEWaite/docker-lfs/blob/d1c3a6a097534a9ce27b6a84c176b14a4595872b/plugins.txt#L3).  Confirmed that it is working as expected.  Would love to see this merged and included in a release.

**Comment by basil** [comment]
Released in [1.5](https://github.com/jenkinsci/adoptopenjdk-plugin/releases/tag/adoptopenjdk-1.5).

**Pull request merged**
