### PR TITLE
Add usage recommendations for production environments

### PR DESCRIPTION
**Pull request by hrmohr**
As suggested by @oleg-nenashev in #8

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Thanks for it!

**Comment by oleg-nenashev** [comment]
A new release would be great once this change is integrated

**Comment by hrmohr** [comment]
> A new release would be great once this change is integrated

Version 1.2 has now been released.

**Comment by oleg-nenashev** [comment]
Thanks a lot! #1 probably needs to be moved to the missing 1.1 release, but the rest looks good

**Pull request merged**
